a=input('Digite algo ')
print('Qual o tipo Primitivo ', type(a))
print ('So tem espaço?', a.isspace())
print ('E um número?', a.isnumeric())
print ('E alfabeto?', a.isalpha())
print ('E alfanumérico? ', a.isalnum())
print ('Esta em maiusculas? ', a.isupper())
print ('Esta em minusculas? ', a.islower())
print ('Esta capitalizada? ', a.istitle())
